version: '3.7'

services:

  flask:
    build: ./flask/
    command: "python app.py"
    ports:
      - 8000:8000
    volumes:
      - $VOLUMES_FOLDER/flask/app:/usr/src/app/
    networks:
      - my_app-network

  mongo:
    build: ./mongo/
    volumes:
      - $VOLUMES_FOLDER/mongo/db:/data/db 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - my_app-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - my_app-network


networks:
  my_app-network:    #Change the name from my_app to some relevant name

